---

- hosts: all
  tasks:
  - name: epel install
    yum: name=epel-release state=latest

  - name: nginx install
    yum: name=nginx state=latest

  - name: nginx start
    service: name=nginx state=started enabled=yes
